spring:
  application:
    name: chatbot
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.dqdozshjpydgkstvjspa
    password: n7x6zPFv2BKa00jg
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL}
      chat:
        enabled: true
        options:
          model: llama3.1
      embedding:
        enabled: true
        options:
          model: nomic-embed-text
#    openai:
#      base-url: https://api.openai.com
#      api-key: ${OPENAI_APIKEY}
#      embedding:
#        enabled: false
#        options:
#          model: text-embedding-3-small
    vectorstore:
      pgvector:
        schema-name: public
        table-name: vector_store3
        initialize-schema: true
        schema-validation: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
application:
  basic-auth: YWRtaW46YWRtaW4xMjM0IQ==
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE




